# Generated by Django 4.2.7 on 2023-11-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
    ]
